repos:
  - repo: local
    hooks:
      - id: spotless
        name: Spotless
        entry: ./gradlew spotlessApply
        language: system
        files: \.java$
        stages: [commit]


  - repo: local
    hooks:
      - id: google-java-format
        name: Google Java Format
        entry: ./gradlew googleJavaFormat
        language: system
        files: \.java$
        stages: [commit]
